"""New config variable"""
from homeassistant.components.weather import (
    ATTR_CONDITION_CLEAR_NIGHT,
    ATTR_CONDITION_CLOUDY,
    ATTR_CONDITION_FOG,
    ATTR_CONDITION_LIGHTNING,
    ATTR_CONDITION_LIGHTNING_RAINY,
    ATTR_CONDITION_PARTLYCLOUDY,
    ATTR_CONDITION_POURING,
    ATTR_CONDITION_RAINY,
    ATTR_CONDITION_SNOWY,
    ATTR_CONDITION_SNOWY_RAINY,
    ATTR_CONDITION_SUNNY,
    ATTR_CONDITION_WINDY,
    ATTR_CONDITION_WINDY_VARIANT,
)

CONF_AREAS = "areas"
CONF_RAIN = "rain"
CONF_SENSOR = "sensor"
CONF_WEATHER = "weather"

DOMAIN = "nea_sg_weather"
ATTRIBUTION = "Weather data from Singapore's NEA"
DEFAULT_NAME = "Singapore Weather"
DEFAULT_SCAN_INTERVAL = 15
DEFAULT_TIMEOUT = 60
HEADERS = {
    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36",
    "referer": "https://www.nea.gov.sg",
}
RAIN_MAP_HEADERS = {
    "authority": "www.weather.gov.sg",
    "referer": "https://www.nea.gov.sg/weather/rain-areas",
    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36",
}
RAIN_MAP_URL_PREFIX = "https://www.weather.gov.sg/files/rainarea/50km/v2/dpsri_70km_"
RAIN_MAP_URL_SUFFIX = "0000dBR.dpsri.png"
RAIN_MAP_GIF_URL = "https://www.weather.gov.sg/weather-rain-area-50km/"

FORECAST_ICON_BASE_URL = "https://www.nea.gov.sg/assets/images/icons/weather-bg/"

MAP_CONDITION = {
    "Mist": ATTR_CONDITION_FOG,
    "Cloudy": ATTR_CONDITION_CLOUDY,
    "Drizzle": ATTR_CONDITION_RAINY,
    "Fair": ATTR_CONDITION_SUNNY,
    "Fair (Day)": ATTR_CONDITION_SUNNY,
    "Fog": ATTR_CONDITION_FOG,
    "Fair (Night)": ATTR_CONDITION_CLEAR_NIGHT,
    "Fair & Warm": ATTR_CONDITION_SUNNY,
    "Heavy Thundery Showers with Gusty Winds": ATTR_CONDITION_LIGHTNING,
    "Heavy Rain": ATTR_CONDITION_POURING,
    "Heavy Showers": ATTR_CONDITION_POURING,
    "Heavy Thundery Showers": ATTR_CONDITION_LIGHTNING,
    "Hazy": ATTR_CONDITION_FOG,
    "Slightly Hazy": ATTR_CONDITION_FOG,
    "Light Rain": ATTR_CONDITION_RAINY,
    "Light Showers": ATTR_CONDITION_RAINY,
    "Overcast": ATTR_CONDITION_CLOUDY,
    "Partly Cloudy": ATTR_CONDITION_PARTLYCLOUDY,
    "Partly Cloudy (Day)": ATTR_CONDITION_PARTLYCLOUDY,
    "Partly Cloudy (Night)": ATTR_CONDITION_PARTLYCLOUDY,
    "Passing Showers": ATTR_CONDITION_RAINY,
    "Moderate Rain": ATTR_CONDITION_RAINY,
    "Showers": ATTR_CONDITION_RAINY,
    "Strong Winds, Showers": ATTR_CONDITION_POURING,
    "Snow": ATTR_CONDITION_SNOWY,
    "Strong Winds, Rain": ATTR_CONDITION_RAINY,
    "Snow Showers": ATTR_CONDITION_SNOWY_RAINY,
    "Sunny": ATTR_CONDITION_SUNNY,
    "Strong Winds": ATTR_CONDITION_WINDY,
    "Thundery Showers": ATTR_CONDITION_LIGHTNING_RAINY,
    "Windy, Cloudy": ATTR_CONDITION_WINDY_VARIANT,
    "Windy": ATTR_CONDITION_WINDY,
    "Windy, Fair": ATTR_CONDITION_WINDY,
    "Windy, Rain": ATTR_CONDITION_RAINY,
    "Windy, Showers": ATTR_CONDITION_RAINY,
}

FORECAST_ICON_MAP_CONDITION = {
    "Mist": "BR",
    "Cloudy": "CL",
    "Drizzle": "DR",
    "Fair": "FA",
    "Fair (Day)": "FA",
    "Fog": "FG",
    "Fair (Night)": "FN",
    "Fair & Warm": "FW",
    "Heavy Thundery Showers with Gusty Winds": "HG",
    "Heavy Rain": "HR",
    "Heavy Showers": "HS",
    "Heavy Thundery Showers": "HT",
    "Hazy": "HZ",
    "Slightly Hazy": "LH",
    "Light Rain": "LR",
    "Light Showers": "LS",
    "Overcast": "OC",
    "Partly Cloudy": "PC",
    "Partly Cloudy (Day)": "PC",
    "Partly Cloudy (Night)": "PN",
    "Passing Showers": "PS",
    "Moderate Rain": "RA",
    "Showers": "SH",
    "Strong Winds, Showers": "SK",
    "Snow": "SN",
    "Strong Winds, Rain": "SR",
    "Snow Showers": "SS",
    "Sunny": "SU",
    "Strong Winds": "SW",
    "Thundery Showers": "TL",
    "Windy, Cloudy": "WC",
    "Windy": "WD",
    "Windy, Fair": "WF",
    "Windy, Rain": "WR",
    "Windy, Showers": "WS",
}

FORECAST_MAP_CONDITION = {
    "thundery showers": ATTR_CONDITION_LIGHTNING_RAINY,
    "partly cloudy": ATTR_CONDITION_PARTLYCLOUDY,
    "rain": ATTR_CONDITION_RAINY,
    "showers": ATTR_CONDITION_RAINY,
    "fair": ATTR_CONDITION_SUNNY,
    "hazy": ATTR_CONDITION_FOG,
    "cloudy": ATTR_CONDITION_CLOUDY,
    "overcast": ATTR_CONDITION_CLOUDY,
    "windy": ATTR_CONDITION_WINDY,
}

AREAS = [
    "Ang Mo Kio",
    "Bedok",
    "Bishan",
    "Boon Lay",
    "Bukit Batok",
    "Bukit Merah",
    "Bukit Panjang",
    "Bukit Timah",
    "Central Water Catchment",
    "Changi",
    "Choa Chu Kang",
    "Clementi",
    "City",
    "Geylang",
    "Hougang",
    "Jalan Bahar",
    "Jurong East",
    "Jurong Island",
    "Jurong West",
    "Kallang",
    "Lim Chu Kang",
    "Mandai",
    "Marine Parade",
    "Novena",
    "Pasir Ris",
    "Paya Lebar",
    "Pioneer",
    "Pulau Tekong",
    "Pulau Ubin",
    "Punggol",
    "Queenstown",
    "Seletar",
    "Sembawang",
    "Sengkang",
    "Sentosa",
    "Serangoon",
    "Southern Islands",
    "Sungei Kadut",
    "Tampines",
    "Tanglin",
    "Tengah",
    "Toa Payoh",
    "Tuas",
    "Western Islands",
    "Western Water Catchment",
    "Woodlands",
    "Yishun",
]

# Rainfall station list sourced from NEA Station Summary (Excel: https://go.gov.sg/station-summary)
# Last updated: 25 Feb 2026. Contains all stations with active rainfall observations (Closed = 0, Rainfall = 1).
# Stations removed vs previous list: S36 (closed), S82 (closed), S89 (closed), S118 (closed),
#   S202, S204, S205, S207, S212, S900 (not in official NEA station list).
# Stations added vs previous list: S06, S07, S23, S25, S60, S64, S80, S92, S102, S117,
#   S300, S302, S306, S308, S902.
# Station names and coordinates updated to match current NEA records where they differed.
RAIN_SENSOR_LIST = [
    {"id": "S06", "device_id": "S06", "name": "Paya Lebar Meteorological Station", "location": {"latitude": 1.356995, "longitude": 103.903962}},
    {"id": "S07", "device_id": "S07", "name": "Macritchie Reservoir", "location": {"latitude": 1.341782, "longitude": 103.833873}},
    {"id": "S08", "device_id": "S08", "name": "Lower Peirce Reservoir", "location": {"latitude": 1.370034, "longitude": 103.827037}},
    {"id": "S23", "device_id": "S23", "name": "Tengah Meteorological Station", "location": {"latitude": 1.3858, "longitude": 103.7119}},
    {"id": "S24", "device_id": "S24", "name": "Changi Meteorological Station", "location": {"latitude": 1.3678, "longitude": 103.9823}},
    {"id": "S25", "device_id": "S25", "name": "Seletar Meteorological Station", "location": {"latitude": 1.41284, "longitude": 103.86922}},
    {"id": "S33", "device_id": "S33", "name": "Jurong Pier Road", "location": {"latitude": 1.3082, "longitude": 103.71}},
    {"id": "S35", "device_id": "S35", "name": "Old Toh Tuck Road", "location": {"latitude": 1.3325, "longitude": 103.755}},
    {"id": "S40", "device_id": "S40", "name": "Mandai Lake Road", "location": {"latitude": 1.403511, "longitude": 103.789647}},
    {"id": "S43", "device_id": "S43", "name": "Kim Chuan Road", "location": {"latitude": 1.340583, "longitude": 103.888138}},
    {"id": "S44", "device_id": "S44", "name": "Nanyang Avenue", "location": {"latitude": 1.34563, "longitude": 103.680669}},
    {"id": "S50", "device_id": "S50", "name": "Clementi Road", "location": {"latitude": 1.3318, "longitude": 103.7762}},
    {"id": "S60", "device_id": "S60", "name": "Artillery Avenue (Sentosa)", "location": {"latitude": 1.250429, "longitude": 103.827494}},
    {"id": "S64", "device_id": "S64", "name": "Bukit Panjang Road", "location": {"latitude": 1.38228, "longitude": 103.76067}},
    {"id": "S66", "device_id": "S66", "name": "Kranji Reservoir", "location": {"latitude": 1.43867, "longitude": 103.73602}},
    {"id": "S69", "device_id": "S69", "name": "Upper Peirce Reservoir", "location": {"latitude": 1.3704, "longitude": 103.8046}},
    {"id": "S71", "device_id": "S71", "name": "Kent Ridge Road", "location": {"latitude": 1.292321, "longitude": 103.78162}},
    {"id": "S77", "device_id": "S77", "name": "Alexandra Road", "location": {"latitude": 1.293506, "longitude": 103.812588}},
    {"id": "S78", "device_id": "S78", "name": "Poole Road", "location": {"latitude": 1.30703, "longitude": 103.89067}},
    {"id": "S79", "device_id": "S79", "name": "Somerset Road", "location": {"latitude": 1.3003, "longitude": 103.8372}},
    {"id": "S80", "device_id": "S80", "name": "Sembawang Meteorological Station", "location": {"latitude": 1.424748, "longitude": 103.820152}},
    {"id": "S81", "device_id": "S81", "name": "Punggol Central", "location": {"latitude": 1.4028, "longitude": 103.9095}},
    {"id": "S84", "device_id": "S84", "name": "Tampines Avenue 5", "location": {"latitude": 1.34428, "longitude": 103.94405}},
    {"id": "S88", "device_id": "S88", "name": "Toa Payoh North", "location": {"latitude": 1.3417, "longitude": 103.8515}},
    {"id": "S90", "device_id": "S90", "name": "Bukit Timah Road", "location": {"latitude": 1.3191, "longitude": 103.8193}},
    {"id": "S92", "device_id": "S92", "name": "South Buona Vista Road", "location": {"latitude": 1.28408, "longitude": 103.78875}},
    {"id": "S94", "device_id": "S94", "name": "Pasir Ris Street 51", "location": {"latitude": 1.3679, "longitude": 103.9489}},
    {"id": "S100", "device_id": "S100", "name": "Sungei Kadut Street 3", "location": {"latitude": 1.4172, "longitude": 103.74855}},
    {"id": "S102", "device_id": "S102", "name": "Semakau Island", "location": {"latitude": 1.190201, "longitude": 103.765725}},
    {"id": "S104", "device_id": "S104", "name": "Woodlands Avenue 9", "location": {"latitude": 1.4439, "longitude": 103.7854}},
    {"id": "S106", "device_id": "S106", "name": "Jalan Noordin (Pulau Ubin)", "location": {"latitude": 1.4168, "longitude": 103.9673}},
    {"id": "S107", "device_id": "S107", "name": "East Coast Park", "location": {"latitude": 1.31332, "longitude": 103.96198}},
    {"id": "S108", "device_id": "S108", "name": "Marina Barrage", "location": {"latitude": 1.28016, "longitude": 103.87074}},
    {"id": "S109", "device_id": "S109", "name": "Ang Mo Kio Avenue 5", "location": {"latitude": 1.37927, "longitude": 103.85002}},
    {"id": "S111", "device_id": "S111", "name": "Scotts Road", "location": {"latitude": 1.310596, "longitude": 103.836438}},
    {"id": "S112", "device_id": "S112", "name": "Lim Chu Kang Road", "location": {"latitude": 1.4388, "longitude": 103.7017}},
    {"id": "S113", "device_id": "S113", "name": "Marine Parade Road", "location": {"latitude": 1.30648, "longitude": 103.9104}},
    {"id": "S114", "device_id": "S114", "name": "Choa Chu Kang Avenue 4", "location": {"latitude": 1.3821, "longitude": 103.7381}},
    {"id": "S115", "device_id": "S115", "name": "Tuas South Avenue 3", "location": {"latitude": 1.293893, "longitude": 103.618442}},
    {"id": "S116", "device_id": "S116", "name": "Pasir Panjang Terminal", "location": {"latitude": 1.282393, "longitude": 103.754713}},
    {"id": "S117", "device_id": "S117", "name": "Banyan Road (Jurong Island)", "location": {"latitude": 1.254152, "longitude": 103.674222}},
    {"id": "S119", "device_id": "S119", "name": "Nicoll Highway", "location": {"latitude": 1.295023, "longitude": 103.86212}},
    {"id": "S120", "device_id": "S120", "name": "Botanic Garden", "location": {"latitude": 1.308092, "longitude": 103.818301}},
    {"id": "S121", "device_id": "S121", "name": "Old Choa Chu Kang Road", "location": {"latitude": 1.373686, "longitude": 103.721772}},
    {"id": "S123", "device_id": "S123", "name": "Towner Road", "location": {"latitude": 1.321376, "longitude": 103.857663}},
    {"id": "S201", "device_id": "S201", "name": "Sunset Way", "location": {"latitude": 1.322941, "longitude": 103.767337}},
    {"id": "S203", "device_id": "S203", "name": "Pasir Panjang Road", "location": {"latitude": 1.292015, "longitude": 103.770516}},
    {"id": "S208", "device_id": "S208", "name": "Changi East Close", "location": {"latitude": 1.31363, "longitude": 104.003165}},
    {"id": "S209", "device_id": "S209", "name": "Yishun Ring Road", "location": {"latitude": 1.421079, "longitude": 103.845177}},
    {"id": "S210", "device_id": "S210", "name": "Woodlands Centre Road", "location": {"latitude": 1.440034, "longitude": 103.769036}},
    {"id": "S211", "device_id": "S211", "name": "Kranji Road", "location": {"latitude": 1.429175, "longitude": 103.757113}},
    {"id": "S213", "device_id": "S213", "name": "Coronation Walk", "location": {"latitude": 1.324273, "longitude": 103.809703}},
    {"id": "S214", "device_id": "S214", "name": "Tanjong Rhu", "location": {"latitude": 1.299106, "longitude": 103.882892}},
    {"id": "S215", "device_id": "S215", "name": "Geylang East Central", "location": {"latitude": 1.31813, "longitude": 103.883031}},
    {"id": "S216", "device_id": "S216", "name": "Ang Mo Kio Avenue 10", "location": {"latitude": 1.360194, "longitude": 103.853344}},
    {"id": "S217", "device_id": "S217", "name": "Bishan Street 13", "location": {"latitude": 1.350278, "longitude": 103.855}},
    {"id": "S218", "device_id": "S218", "name": "Bukit Batok Street 34", "location": {"latitude": 1.364907, "longitude": 103.750648}},
    {"id": "S219", "device_id": "S219", "name": "Yio Chu Kang Road", "location": {"latitude": 1.379983, "longitude": 103.876392}},
    {"id": "S220", "device_id": "S220", "name": "Compassvale Lane", "location": {"latitude": 1.386665, "longitude": 103.89797}},
    {"id": "S221", "device_id": "S221", "name": "Hougang Avenue 1", "location": {"latitude": 1.356909, "longitude": 103.890875}},
    {"id": "S222", "device_id": "S222", "name": "Henderson Road", "location": {"latitude": 1.289872, "longitude": 103.823637}},
    {"id": "S223", "device_id": "S223", "name": "Margaret Drive", "location": {"latitude": 1.299843, "longitude": 103.802646}},
    {"id": "S224", "device_id": "S224", "name": "Airport Boulevard", "location": {"latitude": 1.343944, "longitude": 103.983863}},
    {"id": "S226", "device_id": "S226", "name": "Malan Road", "location": {"latitude": 1.274927, "longitude": 103.803919}},
    {"id": "S227", "device_id": "S227", "name": "Woodlands Drive 62", "location": {"latitude": 1.439979, "longitude": 103.8041}},
    {"id": "S228", "device_id": "S228", "name": "Jurong West Street 73", "location": {"latitude": 1.347033, "longitude": 103.700726}},
    {"id": "S229", "device_id": "S229", "name": "Jurong West Street 42", "location": {"latitude": 1.35193, "longitude": 103.72167}},
    {"id": "S230", "device_id": "S230", "name": "West Coast Road", "location": {"latitude": 1.301667, "longitude": 103.76444}},
    {"id": "S300", "device_id": "S300", "name": "Bedok Reservoir", "location": {"latitude": 1.343065, "longitude": 103.919669}},
    {"id": "S302", "device_id": "S302", "name": "Tengeh Reservoir", "location": {"latitude": 1.33813, "longitude": 103.66303}},
    {"id": "S306", "device_id": "S306", "name": "Murnane Service Reservoir", "location": {"latitude": 1.350849, "longitude": 103.785966}},
    {"id": "S308", "device_id": "S308", "name": "Seletar Reservoir", "location": {"latitude": 1.401584, "longitude": 103.808133}},
    {"id": "S902", "device_id": "S902", "name": "Yishun Walk", "location": {"latitude": 1.41457, "longitude": 103.83106}},
]

REGIONS = ["West", "East", "Central", "South", "North"]

PRIMARY_ENDPOINTS = {
    "forecast2hr": "https://api-open.data.gov.sg/v2/real-time/api/two-hr-forecast",
    "forecast24hr": "https://api-open.data.gov.sg/v2/real-time/api/twenty-four-hr-forecast",
    "temperature": "https://api-open.data.gov.sg/v2/real-time/api/air-temperature",
    "humidity": "https://api-open.data.gov.sg/v2/real-time/api/relative-humidity",
    "wind-direction": "https://api-open.data.gov.sg/v2/real-time/api/wind-direction",
    "wind-speed": "https://api-open.data.gov.sg/v2/real-time/api/wind-speed",
    "forecast4day": "https://api-open.data.gov.sg/v2/real-time/api/four-day-outlook",
    "rainfall": "https://api-open.data.gov.sg/v2/real-time/api/rainfall",
    "uv-index": "https://api-open.data.gov.sg/v2/real-time/api/uv",
    "pm25": "https://api-open.data.gov.sg/v2/real-time/api/pm25",
}

SECONDARY_ENDPOINTS = {
    "forecast2hr": "https://www.nea.gov.sg/api/WeatherForecast/forecast24hrnowcast2hrs/",
    "forecast24hr": "https://www.nea.gov.sg/api/WeatherForecast/forecast24hrnowcast2hrs/",
    "temperature": "",
    "humidity": "",
    "wind-direction": "",
    "wind-speed": "",
    "forecast4day": "https://www.nea.gov.sg/api/Weather4DayOutlook/GetData/",
    "rainfall": "",
    "uv-index": "",
    "pm25": "",
}
